//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abacus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCUPLOADS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DOCUPLOADS()
        {
            this.DOCUPLOADS_FILES = new HashSet<DOCUPLOADS_FILES>();
        }
    
        public int UPLOAD_ID { get; set; }
        public Nullable<int> STATION_ID { get; set; }
        public Nullable<int> SCHOOLYEAR_ID { get; set; }
        public Nullable<System.DateTime> UPLOAD_DATE { get; set; }
        public string UPLOAD_NAME { get; set; }
        public string UPLOAD_SUMMARY { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DOCUPLOADS_FILES> DOCUPLOADS_FILES { get; set; }
    }
}
