//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abacus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class expSTATION_BALANCE_MONTH
    {
        public int ROWID { get; set; }
        public Nullable<int> ΒΝΣ { get; set; }
        public string ΕΠΩΝΥΜΙΑ { get; set; }
        public Nullable<int> ΣΧΟΛ_ΕΤΟΣ { get; set; }
        public Nullable<int> ΜΗΝΑΣ_ΑΡΙΘΜΟΣ { get; set; }
        public string ΜΗΝΑΣ { get; set; }
        public Nullable<int> ΠΑΙΔΙΑ_ΔΥΝΑΜΗ { get; set; }
        public Nullable<int> ΠΡΟΣΩΠΙΚΟ_ΔΥΝΑΜΗ { get; set; }
        public Nullable<int> ΠΛΗΘΟΣ_ΑΤΟΜΑ { get; set; }
        public Nullable<decimal> ΚΟΣΤΟΣ_ΤΡΟΦΕΙΟ { get; set; }
        public Nullable<decimal> ΚΟΣΤΟΣ_ΚΑΘΑΡΙΟΤΗΤΑ { get; set; }
        public Nullable<decimal> ΚΟΣΤΟΣ_ΓΕΝΙΚΕΣ { get; set; }
        public Nullable<decimal> ΔΑΠΑΝΗ_ΤΡΟΦΕΙΟ { get; set; }
        public Nullable<decimal> ΔΑΠΑΝΗ_ΚΑΘΑΡΙΟΤΗΤΑ { get; set; }
        public Nullable<decimal> ΔΑΠΑΝΗ_ΓΕΝΙΚΕΣ { get; set; }
        public Nullable<decimal> ΥΠΟΛΟΙΠΟ_ΤΡΟΦΕΙΟ { get; set; }
        public Nullable<decimal> ΥΠΟΛΟΙΠΟ_ΚΑΘΑΡΙΟΤΗΤΑ { get; set; }
        public Nullable<decimal> ΥΠΟΛΟΙΠΟ_ΓΕΝΙΚΕΣ { get; set; }
        public Nullable<decimal> ΚΟΣΤΟΣ_ΣΥΝΟΛΟ { get; set; }
        public Nullable<decimal> ΔΑΠΑΝΗ_ΣΥΝΟΛΟ { get; set; }
        public Nullable<decimal> ΥΠΟΛΟΙΠΟ_ΣΥΝΟΛΟ { get; set; }
    }
}
