//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abacus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class METABOLES_REPORT
    {
        public int RECORD_ID { get; set; }
        public Nullable<int> BNS { get; set; }
        public Nullable<int> EMPLOYEE_ID { get; set; }
        public Nullable<int> SCHOOL_YEAR { get; set; }
        public Nullable<int> METABOLI_MONTH { get; set; }
        public string METABOLI_TEXT { get; set; }
        public Nullable<int> METABOLI_YEAR { get; set; }
        public Nullable<int> METABOLI_DAYS { get; set; }
    
        public virtual ΠΡΟΣΩΠΙΚΟ ΠΡΟΣΩΠΙΚΟ { get; set; }
    }
}
