//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abacus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class repΠΑΡΟΥΣΙΕΣ_ΜΗΝΑΣ
    {
        public int CHILD_ID { get; set; }
        public Nullable<int> ΒΝΣ { get; set; }
        public Nullable<int> TMIMA_ID { get; set; }
        public string ΤΜΗΜΑ_ΟΝΟΜΑ { get; set; }
        public Nullable<int> ΑΜ { get; set; }
        public string ΟΝΟΜΑΤΕΠΩΝΥΜΟ { get; set; }
        public Nullable<int> ΠΛΗΘΟΣ { get; set; }
        public Nullable<int> PAROUSIA_MONTH { get; set; }
        public int SCHOOLYEAR_ID { get; set; }
        public string ΣΧΟΛΙΚΟ_ΕΤΟΣ { get; set; }
        public string ΠΑΤΡΩΝΥΜΟ { get; set; }
    }
}
