//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abacus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class sqlADMIN_LOGINS
    {
        public int LOGIN_ID { get; set; }
        public string ADMIN_NAME { get; set; }
        public Nullable<System.DateTime> LOGIN_DATETIME { get; set; }
    }
}
