//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abacus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class sqlPRODUCT_LIST
    {
        public int ΠΡΟΙΟΝ_ΚΩΔ { get; set; }
        public string ΚΑΤΗΓΟΡΙΑ { get; set; }
        public string ΠΡΟΙΟΝ_ΛΕΚΤΙΚΟ { get; set; }
        public string ΜΟΝΑΔΑ { get; set; }
        public int ΜΟΝΑΔΑ_ΚΩΔ { get; set; }
        public int ΚΑΤΗΓΟΡΙΑ_ΚΩΔ { get; set; }
        public Nullable<int> ΔΑΠΑΝΗ_ΚΩΔ { get; set; }
        public string ΕΙΔΟΣ_ΛΕΚΤΙΚΟ { get; set; }
        public Nullable<int> ΠΡΟΙΟΝ_ΦΠΑ { get; set; }
        public Nullable<decimal> FPA_VALUE { get; set; }
        public Nullable<int> ΒΝΣ { get; set; }
    }
}
