//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abacus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class sqlPERSONNEL_INFO
    {
        public int PERSONNEL_ID { get; set; }
        public int ΣΤΑΘΜΟΣ_ΚΩΔ { get; set; }
        public string ΒΝΣ_ΕΠΩΝΥΜΙΑ { get; set; }
        public Nullable<int> ΜΗΤΡΩΟ { get; set; }
        public string ΑΦΜ { get; set; }
        public string ΟΝΟΜΑΤΕΠΩΝΥΜΟ { get; set; }
        public string ΠΑΤΡΩΝΥΜΟ { get; set; }
        public string ΜΗΤΡΩΝΥΜΟ { get; set; }
        public string ΦΥΛΟ { get; set; }
        public Nullable<int> ΕΤΟΣ_ΓΕΝΝΗΣΗ { get; set; }
        public Nullable<int> ΗΛΙΚΙΑ { get; set; }
        public string ΔΙΕΥΘΥΝΣΗ { get; set; }
        public string ΤΗΛΕΦΩΝΑ { get; set; }
        public string EMAIL { get; set; }
        public string EIDIKOTITA_CODE { get; set; }
        public string EIDIKOTITA_TEXT { get; set; }
        public string PROSOPIKO_TEXT { get; set; }
        public string ΠΕΡΙΦΕΡΕΙΑΚΗ { get; set; }
        public Nullable<bool> ΑΠΟΧΩΡΗΣΕ { get; set; }
    }
}
