//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abacus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class sqlTMIMATA_INFO
    {
        public int ΤΜΗΜΑ_ΚΩΔ { get; set; }
        public int SCHOOLYEAR_ID { get; set; }
        public Nullable<int> ΒΝΣ { get; set; }
        public string ΣΧΟΛΙΚΟ_ΕΤΟΣ { get; set; }
        public string ΤΜΗΜΑ_ΟΝΟΜΑ { get; set; }
        public string ΒΝΣ_ΟΝΟΜΑ { get; set; }
        public string ΠΕΡΙΦΕΡΕΙΑΚΗ { get; set; }
    }
}
