//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abacus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class sqlΣΥΝΟΛΟ_ΓΕΝΙΚΗ_ΗΜΕΡΑ
    {
        public int ROWID { get; set; }
        public Nullable<int> ΒΝΣ { get; set; }
        public Nullable<int> ΣΧΟΛ_ΕΤΟΣ { get; set; }
        public string ΕΠΩΝΥΜΙΑ { get; set; }
        public Nullable<System.DateTime> ΗΜΕΡΟΜΗΝΙΑ { get; set; }
        public string ΜΗΝΑΣ { get; set; }
        public Nullable<decimal> TOTAL_DAY { get; set; }
        public Nullable<int> ΜΗΝΑΣ_ΑΡΙΘΜΟΣ { get; set; }
    }
}
