//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abacus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class srcABSENCE_DAYS
    {
        public int ROWID { get; set; }
        public Nullable<int> ΒΝΣ { get; set; }
        public Nullable<int> ΥΠΑΛΛΗΛΟΣ_ΚΩΔ { get; set; }
        public Nullable<int> ΣΧΟΛΙΚΟ_ΕΤΟΣ { get; set; }
        public Nullable<int> ΜΕΤΑΒΟΛΗ_ΜΗΝΑΣ { get; set; }
        public Nullable<int> ΜΕΡΕΣ_ΑΠΟΥΣΙΑ { get; set; }
    }
}
