//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abacus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class srcPERSONNEL_DATA
    {
        public int PERSONNEL_ID { get; set; }
        public Nullable<int> ΒΝΣ { get; set; }
        public string ΒΝΣ_ΕΠΩΝΥΜΙΑ { get; set; }
        public Nullable<int> ΜΗΤΡΩΟ { get; set; }
        public string ΟΝΟΜΑΤΕΠΩΝΥΜΟ { get; set; }
        public string ΚΛΑΔΟΣ_ΚΩΔΙΚΟΣ { get; set; }
        public string ΒΑΘΜΟΣ_ΛΕΚΤΙΚΟ { get; set; }
        public string ΑΠΟΦΑΣΗ_ΦΕΚ { get; set; }
    }
}
