//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abacus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ΓΕΥΜΑΤΑ_ΠΡΩΙ
    {
        public int ΠΡΩΙΝΟ_ΚΩΔ { get; set; }
        public string ΠΡΩΙΝΟ { get; set; }
        public string ΣΧΟΛΙΟ { get; set; }
        public Nullable<int> ΒΝΣ { get; set; }
    }
}
