//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abacus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ΔΑΠΑΝΕΣ_ΕΙΔΗ
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ΔΑΠΑΝΕΣ_ΕΙΔΗ()
        {
            this.ΠΡΟΙΟΝ_ΚΑΤΗΓΟΡΙΑ = new HashSet<ΠΡΟΙΟΝ_ΚΑΤΗΓΟΡΙΑ>();
        }
    
        public int ΕΙΔΟΣ_ΚΩΔ { get; set; }
        public string ΕΙΔΟΣ_ΛΕΚΤΙΚΟ { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ΠΡΟΙΟΝ_ΚΑΤΗΓΟΡΙΑ> ΠΡΟΙΟΝ_ΚΑΤΗΓΟΡΙΑ { get; set; }
    }
}
