//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abacus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ΔΑΠΑΝΗ_ΚΑΘΑΡΙΟΤΗΤΑ
    {
        public int ΚΩΔΙΚΟΣ { get; set; }
        public Nullable<int> ΒΝΣ { get; set; }
        public Nullable<int> ΣΧΟΛ_ΕΤΟΣ { get; set; }
        public Nullable<System.DateTime> ΗΜΕΡΟΜΗΝΙΑ { get; set; }
        public Nullable<int> ΚΑΤΗΓΟΡΙΑ { get; set; }
        public Nullable<int> ΠΡΟΙΟΝ { get; set; }
        public Nullable<decimal> ΠΟΣΟΤΗΤΑ { get; set; }
        public Nullable<decimal> ΤΙΜΗ_ΜΟΝΑΔΑ { get; set; }
        public Nullable<decimal> ΣΥΝΟΛΟ { get; set; }
    
        public virtual ΠΡΟΙΟΝ_ΚΑΤΗΓΟΡΙΑ ΠΡΟΙΟΝ_ΚΑΤΗΓΟΡΙΑ { get; set; }
    }
}
