//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abacus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ΔΙΑΙΤΟΛΟΓΙΟ_ΗΜΕΡΑ
    {
        public int ΔΙΑΙΤΟΛΟΓΙΟ_ΚΩΔ { get; set; }
        public Nullable<int> ΣΤΑΘΜΟΣ_ΚΩΔ { get; set; }
        public Nullable<System.DateTime> ΗΜΕΡΟΜΗΝΙΑ { get; set; }
        public Nullable<int> ΓΕΥΜΑ_ΠΡΩΙ { get; set; }
        public Nullable<int> ΓΕΥΜΑ_ΜΕΣΗΜΕΡΙ { get; set; }
        public Nullable<int> ΓΕΥΜΑ_ΒΡΕΦΗ { get; set; }
        public Nullable<int> ΤΡΟΦΙΜΟΙ { get; set; }
        public Nullable<int> ΠΡΟΣΩΠΙΚΟ { get; set; }
        public Nullable<int> ΠΛΗΘΟΣ { get; set; }
        public Nullable<decimal> ΚΟΣΤΟΣ { get; set; }
        public Nullable<decimal> ΔΑΠΑΝΗ { get; set; }
    }
}
