//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abacus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ΙΣΟΖΥΓΙΟ_ΜΗΝΑΣ
    {
        public int BALANCE_ID { get; set; }
        public Nullable<int> STATION_ID { get; set; }
        public Nullable<int> SCHOOLYEAR_ID { get; set; }
        public Nullable<int> MONTH_ID { get; set; }
        public Nullable<int> CHILDREN_NUMBER { get; set; }
        public Nullable<int> PERSONNEL_NUMBER { get; set; }
        public Nullable<int> PERSONS_NUMBER { get; set; }
        public Nullable<decimal> COST_FEED { get; set; }
        public Nullable<decimal> COST_CLEAN { get; set; }
        public Nullable<decimal> COST_OTHER { get; set; }
        public Nullable<decimal> EXPENSE_FEED { get; set; }
        public Nullable<decimal> EXPENSE_CLEAN { get; set; }
        public Nullable<decimal> EXPENSE_OTHER { get; set; }
        public Nullable<decimal> BALANCE_FEED { get; set; }
        public Nullable<decimal> BALANCE_CLEAN { get; set; }
        public Nullable<decimal> BALANCE_OTHER { get; set; }
        public Nullable<decimal> COST_TOTAL { get; set; }
        public Nullable<decimal> EXPENSE_TOTAL { get; set; }
        public Nullable<decimal> BALANCE_TOTAL { get; set; }
    }
}
