//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abacus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ΠΑΙΔΙΑ_ΕΓΓΡΑΦΕΣ
    {
        public int ΕΓΓΡΑΦΗ_ΚΩΔ { get; set; }
        public Nullable<int> ΠΑΙΔΙ_ΚΩΔ { get; set; }
        public Nullable<int> ΒΝΣ { get; set; }
        public Nullable<int> ΤΜΗΜΑ { get; set; }
        public Nullable<System.DateTime> ΗΜΝΙΑ_ΕΓΓΡΑΦΗ { get; set; }
        public Nullable<System.DateTime> ΗΜΝΙΑ_ΠΕΡΑΣ { get; set; }
        public Nullable<int> ΣΧΟΛΙΚΟ_ΕΤΟΣ { get; set; }
    
        public virtual ΠΑΙΔΙΑ ΠΑΙΔΙΑ { get; set; }
    }
}
