//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abacus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ΠΡΟΙΟΝΤΑ_ΒΝΣ
    {
        public int ΠΡΟΙΟΝ_ΚΩΔ { get; set; }
        public string ΠΡΟΙΟΝ_ΛΕΚΤΙΚΟ { get; set; }
        public Nullable<int> ΠΡΟΙΟΝ_ΜΟΝΑΔΑ { get; set; }
        public Nullable<int> ΠΡΟΙΟΝ_ΚΑΤΗΓΟΡΙΑ { get; set; }
        public Nullable<int> ΠΡΟΙΟΝ_ΦΠΑ { get; set; }
        public Nullable<int> ΒΝΣ { get; set; }
    }
}
