//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abacus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ΠΡΟΣΩΠΙΚΟ_ΜΕΤΑΒΟΛΕΣ
    {
        public int ΜΕΤΑΒΟΛΗ_ΚΩΔ { get; set; }
        public Nullable<int> ΒΝΣ { get; set; }
        public Nullable<int> ΥΠΑΛΛΗΛΟΣ_ΚΩΔ { get; set; }
        public Nullable<System.DateTime> ΗΜΝΙΑ_ΑΠΟ { get; set; }
        public Nullable<System.DateTime> ΗΜΝΙΑ_ΕΩΣ { get; set; }
        public Nullable<int> ΗΜΕΡΕΣ { get; set; }
        public Nullable<int> ΣΧΟΛΙΚΟ_ΕΤΟΣ { get; set; }
        public Nullable<int> ΜΕΤΑΒΟΛΗ_ΜΗΝΑΣ { get; set; }
        public Nullable<int> ΜΕΤΑΒΟΛΗ_ΕΙΔΟΣ { get; set; }
    
        public virtual ΠΡΟΣΩΠΙΚΟ ΠΡΟΣΩΠΙΚΟ { get; set; }
    }
}
