//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abacus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ΠΡΟΣΩΠΙΚΟ
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ΠΡΟΣΩΠΙΚΟ()
        {
            this.ΤΜΗΜΑ_ΠΑΙΔΑΓΩΓΟΣ = new HashSet<ΤΜΗΜΑ_ΠΑΙΔΑΓΩΓΟΣ>();
            this.ΠΡΟΓΡΑΜΜΑ_ΗΜΕΡΑ = new HashSet<ΠΡΟΓΡΑΜΜΑ_ΗΜΕΡΑ>();
            this.ΠΡΟΣΩΠΙΚΟ_ΜΕΤΑΒΟΛΕΣ = new HashSet<ΠΡΟΣΩΠΙΚΟ_ΜΕΤΑΒΟΛΕΣ>();
            this.METABOLES_REPORT = new HashSet<METABOLES_REPORT>();
        }
    
        public int PERSONNEL_ID { get; set; }
        public Nullable<int> ΒΝΣ { get; set; }
        public Nullable<int> ΜΗΤΡΩΟ { get; set; }
        public string ΑΦΜ { get; set; }
        public string ΕΠΩΝΥΜΟ { get; set; }
        public string ΟΝΟΜΑ { get; set; }
        public string ΠΑΤΡΩΝΥΜΟ { get; set; }
        public string ΜΗΤΡΩΝΥΜΟ { get; set; }
        public Nullable<int> ΕΤΟΣ_ΓΕΝΝΗΣΗ { get; set; }
        public Nullable<int> ΗΛΙΚΙΑ { get; set; }
        public string ΔΙΕΥΘΥΝΣΗ { get; set; }
        public string ΤΗΛΕΦΩΝΑ { get; set; }
        public string EMAIL { get; set; }
        public Nullable<int> ΚΛΑΔΟΣ { get; set; }
        public Nullable<int> ΕΙΔΙΚΟΤΗΤΑ { get; set; }
        public Nullable<int> ΠΡΟΣΩΠΙΚΟ_ΕΙΔΟΣ { get; set; }
        public string ΠΑΡΑΤΗΡΗΣΕΙΣ { get; set; }
        public Nullable<int> ΦΥΛΟ_ΚΩΔ { get; set; }
        public string ΑΠΟΦΑΣΗ_ΦΕΚ { get; set; }
        public Nullable<int> ΒΑΘΜΟΣ { get; set; }
        public Nullable<bool> ΑΠΟΧΩΡΗΣΕ { get; set; }
        public Nullable<int> ΑΠΟΧΩΡΗΣΗ_ΑΙΤΙΑ { get; set; }
        public Nullable<System.DateTime> ΑΠΟΧΩΡΗΣΗ_ΗΜΝΙΑ { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ΤΜΗΜΑ_ΠΑΙΔΑΓΩΓΟΣ> ΤΜΗΜΑ_ΠΑΙΔΑΓΩΓΟΣ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ΠΡΟΓΡΑΜΜΑ_ΗΜΕΡΑ> ΠΡΟΓΡΑΜΜΑ_ΗΜΕΡΑ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ΠΡΟΣΩΠΙΚΟ_ΜΕΤΑΒΟΛΕΣ> ΠΡΟΣΩΠΙΚΟ_ΜΕΤΑΒΟΛΕΣ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<METABOLES_REPORT> METABOLES_REPORT { get; set; }
    }
}
