//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abacus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ΣΥΣ_ΑΑ_ΛΑΤΙΝΙΚΟΙ
    {
        public int AA_ID { get; set; }
        public string AA_TEXT { get; set; }
    }
}
