//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abacus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ΣΥΣ_ΕΙΔΙΚΟΤΗΤΕΣ
    {
        public int EIDIKOTITA_ID { get; set; }
        public string EIDIKOTITA_TEXT { get; set; }
        public Nullable<int> KLADOS { get; set; }
        public string EIDIKOTITA_CODE { get; set; }
    
        public virtual ΣΥΣ_ΚΛΑΔΟΙ ΣΥΣ_ΚΛΑΔΟΙ { get; set; }
    }
}
