//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abacus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ΣΥΣ_ΠΕΡΙΦΕΡΕΙΕΣ
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ΣΥΣ_ΠΕΡΙΦΕΡΕΙΕΣ()
        {
            this.ΣΥΣ_ΔΗΜΟΙ = new HashSet<ΣΥΣ_ΔΗΜΟΙ>();
        }
    
        public int PERIFERIA_ID { get; set; }
        public string PERIFERIA_NAME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ΣΥΣ_ΔΗΜΟΙ> ΣΥΣ_ΔΗΜΟΙ { get; set; }
    }
}
