//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abacus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ΤΜΗΜΑ
    {
        public int ΤΜΗΜΑ_ΚΩΔ { get; set; }
        public Nullable<int> ΒΝΣ { get; set; }
        public Nullable<int> ΣΧΟΛΙΚΟ_ΕΤΟΣ { get; set; }
        public Nullable<int> ΚΑΤΗΓΟΡΙΑ { get; set; }
        public Nullable<int> ΑΥΞΩΝ_ΑΡΙΘΜΟΣ { get; set; }
        public string ΧΑΡΑΚΤΗΡΙΣΜΟΣ { get; set; }
        public string ΟΝΟΜΑΣΙΑ { get; set; }
    
        public virtual ΣΥΣ_ΣΤΑΘΜΟΙ ΣΥΣ_ΣΤΑΘΜΟΙ { get; set; }
        public virtual ΤΜΗΜΑ_ΚΑΤΗΓΟΡΙΑ ΤΜΗΜΑ_ΚΑΤΗΓΟΡΙΑ { get; set; }
    }
}
