//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abacus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ΤΜΗΜΑ_ΚΑΤΗΓΟΡΙΑ
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ΤΜΗΜΑ_ΚΑΤΗΓΟΡΙΑ()
        {
            this.ΤΜΗΜΑ = new HashSet<ΤΜΗΜΑ>();
        }
    
        public int CATEGORY_ID { get; set; }
        public string CATEGORY_TEXT { get; set; }
        public Nullable<decimal> AGE_START { get; set; }
        public Nullable<decimal> AGE_END { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ΤΜΗΜΑ> ΤΜΗΜΑ { get; set; }
    }
}
