//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abacus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ΤΡΟΦΕΙΟ_ΑΤΟΜΟ
    {
        public int ID { get; set; }
        public Nullable<int> STATION_ID { get; set; }
        public Nullable<int> SCHOOLYEARID { get; set; }
        public Nullable<decimal> COST_PERSON { get; set; }
    
        public virtual ΣΥΣ_ΣΤΑΘΜΟΙ ΣΥΣ_ΣΤΑΘΜΟΙ { get; set; }
    }
}
